### ISSUE TITLE
Proper logging of PetaVision output

### ISSUE THREAD

**Issue by slundqui** [PetaVision/OpenPV#11]
Hi all,
I've implemented MPI across batches. Please see the blog post for further information:
https://petavision.github.io/jekyll/update/2015/08/19/batching-across-mpi.html

One of the downsides of MPI across batches is that each MPI batch will print to the screen simultaneously, which is why I would like to propose a proper fix for logging output of PetaVision. Currently, the code is scattered with random _printf()_ and _std::cout_ calls to print, with only some of them surrounded by a global rank if statement. It would be nice to write wrappers around both of these functions. Not only will this clean up the code by adding rank checks in a centralized place in the code, but this will also allow us to properly redirect logging into, say, a text file instead of stdout. I've looked briefly into this, and it seems the hardest part of this is to still support the _std::cout << "my text here\n";_ syntax for printing, as we need to make a subclass of ostreams.

Sheng

**Comment by dpaiton** [comment]
I think this is a great idea. I think all prints should  be wrapped. Could we also just force an easier syntax (printf style)?

**Comment by slundqui** [comment]
Me and Pete have been arguing over which print statements we prefer. Personally, i think the cout style printing is much more robust and intuitive as opposed to the printf style, so I would request that we still allow for such a printing mechanism.

**Comment by dpaiton** [comment]
I agree that cout is easier. I guess the question is whether that ease and intuitive use is worth the extra coding effort. However, I'm not the one writing up the code, so I'll abstain from voting.

**Comment by peteschultz** [comment]
Originally, everything was printf and fprintf because the standard library doesn't play well with line debuggers.  There may have been other reasons but that's the one I was told.  Because of the large number of both printf/fprintf occurrences cout/cerr occurrences that are in the code now, I would argue against an attempt to convert to all one or all the other.  When it comes to printing to stdout or stderr, I don't think the robustness C++ adds is an issue, but writing to a std::stringstream is certainly more robust than using sprintf or snprintf.

**Comment by riskybacon** [comment]
Pete and I just discussed some changes to make to pv_assert:

if MPI is compiled and enabled, put in an MPI_Barrier before exiting. Same thing for exitFailure().

These functions are located in PVAssert.cpp and PVLog.cpp, respectively. 

It isn't clear to me how to get the MPI_comm communicator inside these functions.

**Comment by peteschultz** [comment]
I just made a pull request (#71) that addresses many of the logging issues.  Thanks to Jeff @riskybacon for providing a lot of assistance.  This passed all system tests on my Ubuntu laptop, but I haven't had the chance to test this on OS X.  This pull request doesn't close all the difficulties related to logfiles, but the current state of the pull request is an improvement (assuming it can be made to work on the Mac) over the current state of the develop branch, and it addresses the most labor-intensive part: converting the large amount of stdout/stderr-based statements in OpenPV to PVLog-related statements.

Briefly, there are now six logging behaviors defined in PVLog.cpp/PVLog.hpp: pvInfo, pvWarn, pvError, pvErrorNoExit, pvDebug, and pvStackTrace.  Warn and pvErrorNoExit are new, and pvError has different behavior.  pvWarn prefixes the output with "WARN " but no file or line number.  pvError now exits when its destructor is called.  pvErrorNoExit has the same prefix ("ERROR file:line: ") as pvError but doesn't exit.

These PVLog-defined classes also take a printf method, which internally creates a temporary string and sends it to the stream using operator<<.  This eliminates the need to convert printf-style statements to C++-style shift-operator statements.  Hence, it would be easy to convert projects to use PVLog methods throughout:
- `printf(...)` -> `pvInfo().printf(...)`
- `fprintf(stderr, ...)` -> `pvWarn().printf(...)` or pvErrorNoExit().printf(...)`
- `std::cout << X << Y` -> `pvInfo() << X << Y`
- `std::cerr << X << Y` -> `pvWarn().printf(...)` or `pvErrorNoExit().printf(...)`
  Note, however, that I found many instances in OpenPV where informational-type messages were sent to stderr, and warning or error messages were sent to stdout.  Once the initial conversion of a project is made, it would make sense to consider in more detail which logging type was needed for which print-statement.

Please provide your input on this pull request.  I'd like to merge it into the develop branch by the end of the week.

**Comment by peteschultz** [comment]
I just pushed the commit https://github.com/PetaVision/OpenPV/commit/aabf5601a3b6be7a5c117aa602c8d702786d7e60, which is a squashed rebase of this pull request onto the develop brancht; and I'm closing this issue.
