### ISSUE TITLE
Clean up Matlab & Python analysis code

### ISSUE THREAD

**Issue by dpaiton** [PetaVision/OpenPV#14]
There is a lot of repeated and broken analysis code floating around. Enough that the OpenPV primary language automagically marked by GitHub is 'matlab'. Since the repository size is a constraint we are all aware of, it makes sense that a spring cleaning should be in order.

Steps to complete this:

First everyone should verify that code they have authored is still working and still necessary. This includes code in the 'projects' folder.

Next we have to go through legacy code and start wholesale deprecating stuff that doesn't work any more. 

After a while, the deprecated code should be moved off of the repository into an archived folder on the NMC servers.

**Comment by slundqui** [comment]
I think much of the extra analysis code exists in the projects directory. While I do believe that we should try to make one set of coherent analysis scripts, I believe this problem essentially stems to the fact that the projects directory is in the repository. Furthermore, our current goal for analysis is to move away from matlab/python analysis, but rather to have PetaVision itself (via probes) make the actual figures. Hopefully, this will obsolete much of the broken/repeated analysis code floating around.

**Comment by dpaiton** [comment]
While I don't disagree entirely, I do believe there is also a lot of broken and repeat code here: https://github.com/PetaVision/OpenPV/tree/master/pv-core/analysis

I think cleaning up that folder would help considerably. Regarding the projects dir being in the repo - this is another discussion all together. Given that it is in the repo now, project owners should look into removing unnecessary / old & broken scripts. In a dream world, the analysis code in projects would call a series of analysis functions that are located in the OpenPV/mlab or OpenPV/plab folders which return properly formatted data structures for plotting.

**Comment by peteschultz** [comment]
Right now there are hundreds of *.m and *.py files in pv-core/ directory, almost as many as there C/C++ files.  Should we start by identifying which of them people are currently using regularly? (Probably a very small number.)  Then I'd say that if a script is useful to PetaVision users generally it should stay.  But if it was specialized to a particular application, it probably doesn't belong in pv-core, and whoever is using it should move it into a project directory or just keep it locally.

**Comment by wshainin** [comment]
I just created the branch "cleanup." I will be using this branch to resolve Issue #31, #25, and this one. I will be moving all code that isn't potentially useful to a third party using OpenPV. All project-specific code will be moved to the Projects repo. All non-generic/obsolete/esoteric/useless code (outside of src) will be moved to a local NMC-hosted git repository. The contents of pv-core will be moved to the root of OpenPV. analysis, input, psycho, scripts, and tools will either be removed or liberally thinned. Most of mlab will be moved/removed. 

I'll have to take some care to make sure any references to the current directory structure are updated accordingly, and everything still works. Please provide input if you object, or foresee any problems. 

OpenPV _will_ be categorized as a C++ project, so help me dog.

**Comment by wshainin** [comment]
Cleanup is now merged with develop. Most of the analysis in mlab is gone. The analysis in HyPerLCA is now out of the OpenPV repo, and in the Projects repo. I'm leaving this issue open, because we still need to make some simple analysis tools. Before develop is released, the LCA tutorial should be re-written to reflect the new directory changes, and whatever analysis we are providing.

**Comment by wshainin** [comment]
After reviewing this issue, I think it can be closed. The obsolete/stale/misc analysis code was moved out of the OpenPV repository when the cleanup was finished and merged with master. We have tools to read and write OpenPV 'pvp' files in both Octave/MATLAB and Python. A more feature complete set of analysis tools is needed, but should be in a separate feature request.
