### ISSUE TITLE
Search on documentation is broken

### ISSUE THREAD

**Issue by dpaiton** [PetaVision/OpenPV#15]
When I searched for an item in the PetaVision documentation (http://petavision.github.io/doxygen/) the page that was displayed was the html page, probably index.html? 

I am using Chrome Version 44.0.2403.130 (64-bit) (I think a little out of date - haven't restarted in a while.)

Are others getting this issue? If it's just me then I can provide more info to hunt down the bug.

**Comment by peteschultz** [comment]
I'm getting a window that displays source html source, but not the index page; the html only has buttons for the main page, related pages, and data structures links, and then a couple of script elements.  And I mean that the window shows the html source itself, not a page with any working controls.  That's probably the same thing you're seeing?

**Comment by dpaiton** [comment]
Yup, that's what I got.

**Comment by peteschultz** [comment]
It seems that the search depends on sourceforge in some way.  The searchbox on <petavision.sourceforge.net/doxygen/html/> works fine, but with the sourceforg pages downloaded to my local machine, the result is the same as with the github pages.

**Comment by dpaiton** [comment]
I guess you're working on it now? I just went to take a look a the code it spits out and the behavior has changed. It now downloads a "search.php" file when I click 'return' after typing a search query.

**Comment by peteschultz** [comment]
I don’t _think_ I changed anything regarding the search, although I did rerun doxygen to restore a markdown page that had inadvertently gotten deleted.  None of the configuration files changed though; just a new .md file in doxygen/src and an updated link in an existing doxygen/src.  I got the same new behavior you saw, though.

**Comment by slundqui** [comment]
Fixed via 1f962a4914339b0f4823f1435799cfc32d6d1fc7. Weird search configuration parameter.
