### ISSUE TITLE
Why are hpp files accessible from doxygen but not cpp?

### ISSUE THREAD

**Issue by dpaiton** [PetaVision/OpenPV#16]
For example in http://petavision.github.io/doxygen/classPV_1_1IdentConn.html you can click the hpp and pull up the code but not the cpp. Can we just make links that redirect to the cpp code on github?

**Comment by peteschultz** [comment]
I think the reason there are links to .hpp and not .cpp is that that's where the `/**comment*/`-style blocks that doxygen reads are.  Check on sourceforge (but do it quickly; the sourceforge web pages will be taken down soon): the .cpp files were listed at the bottom of the class reference pages but without a link.   If we want links to the .cpp code it needs to be in a way that doxygen generates the link.  I believe it will be easier to get doxygen to generate *cpp_source.html files in the html/ directory than to get it to link to github.com/PetaVision/master/blob/etc/etc/etc.cpp.  But whichever way, that would be a good thing to have available.

**Comment by dpaiton** [comment]
The Caffe doxygen also links to the hpp files and not the cpp files. If doxygen redirecting to the github.com url is the easiest route, I think that it is the way to go. Github does a good job at displaying source code, and makes it fairly easy to access the rest of the code.

**Comment by peteschultz** [comment]
It looks like all we'd have to do generate *cpp_source.html files and have doxygen create links to them would be to change SOURCE_BROWSER to YES in doxy.cfg.  I don't know of a way to have doxygen link the .cpp lines of the "generated from" section to github.com.

**Comment by peteschultz** [comment]
I updated the doxygen pages so that the bottom section, "the documentation for this class was generated from...," now has a links for both the .cpp and .hpp files.
