### ISSUE TITLE
-d flag doesn't work as expected for mpi batches

### ISSUE THREAD

**Issue by callistabee** [PetaVision/OpenPV#17]
Normally, one can specify the GPU devices for a set of MPI processes by using `-d` with a comma separated list of devices, e.g. `-d 0,1`. However, this does not work when specifying a `-batchwidth` greater than one. Even with `-d 0,1`, both MPI processes are assigned device zero.

**Comment by slundqui** [comment]
Fixed via commit 46a8a4d89fbfd6cb709be08544bf4e19bb4f25da.
