### ISSUE TITLE
Compiling with Cuda 7.5

### ISSUE THREAD

**Issue by slundqui** [PetaVision/OpenPV#19]
Hi all,

I'm currently trying to install PetaVision onto Ubuntu, and seem to have ran into an issue, where the error message says:

```
cc1plus: fatal error: /usr/local/cuda/include: No such file or directory
```

Running with 

```
make VERBOSE=1
```

splits out this command in which it's failing:

/usr/local/cuda/bin/nvcc -M -D__CUDACC__ /home/sheng/workspace/OpenPV/pv-core/./src/arch/cuda/CudaTimer.cu -o /home/sheng/workspace/OpenPV/pv-core/CMakeFiles/pv.dir/./src/arch/cuda/pv_generated_CudaTimer.cu.o.NVCC-depend -ccbin /usr/bin/mpicc -m64 -Xcompiler ,\"-fopenmp\",\"-I\",\"/usr/local/cuda/include\",**\"-I\"**,\"-I\",\"/usr/local/cuda/include\",\"-I\",\"-g3\",\"-O0\" -arch=sm_30 -Xptxas -v -keep -lineinfo -g -G -DNVCC -I/usr/local/cuda/include -I/usr/include/gdal -I/usr/local/cuda/include

Notice the extra -I flag in bold (sorry, couldn't figure out how to make it red or anything in markdown). Taking out this extra -I seems to have fixed the problem. I would look into where this extra -I is being generated, but I have to head off to class, so I'm hoping one of you guys (I mean @peteschultz. Please and thank you) could take a look at this.

Sheng

**Comment by slundqui** [comment]
Sorry, forgot to mention, I'm trying to compile with CUDA version 7.5

**Comment by peteschultz** [comment]
Using CUDA 7.0 I got:

,"-fopenmp","-I","/usr/local/cuda/include","-I","/home/pschultz/local/cuDNN/cuda-7.0//include","-I","/usr/local/cuda/include","-I","/home/peteschultz/local/cuDNN/cuda-7.0//include","-g3","-O0"

The difference between that and Sheng’s run is that his doesn’t have an argument corresponding to "/home/peteschultz/local/cuDNN/cuda-7.0//include” in the two places where they appeared for me.  That suggests to me that the “-I” immediately before “-g3” should also be omitted (it may have interpreted the argument as adding -g3 to the list of include directories).  Or perhaps the directory containing cudnn.h should be inserted after the two occurrences of "-I” that aren’t followed by a path.

Sheng, when you compiled just by removing the orphaned “-I” arguments, how was the compiler able to find cudnn.h when it needed it?

**Comment by slundqui** [comment]
The compiler hasn't actually gotten to that part yet. I found the bug, I had the cudnn path wrong, which I'm guessing is the reason why the orphaned -I arguments were there. Although this brings up another issue, is that it may be useful for cmake to spit out an error when it doesn't find the cudnn path.

**Comment by peteschultz** [comment]
I just pushed a change to pv-core/CMakeLists.txt that checks IS_DIRECTORY on CUDNN_PATH, and also checks for cudnn.h and cudnn.{dylib,so} somewhere in that directory tree.  Please let me know if this works or if you run into any problems with the change.
