### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by dpaiton** [PetaVision/OpenPV#20]
The documentation on http://petavision.github.io/doxygen/md_docs_doxygen_src_install_ubuntu.html is incomplete. Specifically, under Checking Out and Installing PetaVision, it has:
    1 cd ${HOME}
    2 mkdir workspace
    3 cd workspace
    4 git clone https://github.com/PetaVision/OpenPV
    5 ccmake .

which skips the `cd OpenPV` step.

Also, the steps for running the system tests are incorrect.

**Comment by peteschultz** [comment]
It looks like @slundqui moved this page to the wiki at https://github.com/PetaVision/OpenPV/wiki/Ubuntu-Installation; I updated the instructions on that page.  Please check to see if they're correct now.

**Comment by dpaiton** [comment]
Looks good, thanks Pete & Sheng!
