### ISSUE TITLE
CIFAR tutorial: fix extractCIFAR.m script

### ISSUE THREAD

**Issue by sumtopmus** [PetaVision/OpenPV#213]
The script contains a function `extractImagesOctave` as well as several script commands. The current versions of MATLAB/Octave expect to have functions in separate files named accordingly. The solution is to put the function `extractImagesOctave` in a separate file.

**Comment by peteschultz** [comment]
I added this fix to the branch `lcacifar-tutorial-update`, which should get incorporated into the develop branch soon, along with other updates to the tutorial that Austin is working on. Thanks for posting this issue.

**Comment by peteschultz** [comment]
Addressed by <https://github.com/PetaVision/OpenPV/pull/217>
