### ISSUE TITLE
macOS installation: obsolete version of mermaid

### ISSUE THREAD

**Issue by sumtopmus** [PetaVision/OpenPV#214]
The current guide for macOS installation asks to install `mermaid@0.4.0` which is outdated and does not install with `npm` anymore. The up-to-date versions of `mermaid` and `phantomjs` can be installed, the only issue is that the arrows are not drawn and the background is white (was transparent before).

Old image (Linux-made):
![image](https://user-images.githubusercontent.com/4838401/27921907-874440cc-6236-11e7-9172-73d7b95833d0.png)

New image (macOS-made):
![image](https://user-images.githubusercontent.com/4838401/27921936-9bcfa5b8-6236-11e7-8dd0-544f954e9f2f.png)

**Comment by peteschultz** [comment]
The most recent version of phantomjs and mermaid version 7.0.0 seem to fix the arrowhead issue (the color of the legend is as in your macOS-made image). Please try this; if these versions work, we'll update the wiki. Thanks.

**Comment by peteschultz** [comment]
Updated the wiki.
