### ISSUE TITLE
Feature request: make output for norm probe files to be in CSV format

### ISSUE THREAD

**Issue by sumtopmus** [PetaVision/OpenPV#224]
Right now the format is the following:

> t =  0.000 b = 0 numNeurons =     3072 L2-norm squared = 0.000000
> t =  1.000 b = 0 numNeurons =     3072 L2-norm squared = 0.000000
> t =  2.000 b = 0 numNeurons =     3072 L2-norm squared = 7.111025
> t =  3.000 b = 0 numNeurons =     3072 L2-norm squared = 7.109676
> t =  4.000 b = 0 numNeurons =     3072 L2-norm squared = 7.107555

The files weight a lot and this format is not easy to read. I suggest something like this:

> t,b,numNeurons,norm
> 0.000, 0,     3072, 0.000000
> 1.000, 0,     3072, 0.000000
> 2.000, 0,     3072, 7.111025
> 3.000, 0,     3072, 7.109658
> 4.000, 0,     3072, 7.107500

**Comment by peteschultz** [comment]
This change was added in <https://github.com/PetaVision/OpenPV/pull/228>.
