### ISSUE TITLE
Analysis script for LCA Cifar tutorial not working anymore

### ISSUE THREAD

**Issue by mantier** [PetaVision/OpenPV#247]
If you run the tutorial the analysis script is not working out of the box any more (OpenPV/tutorials/LCACifar/scripts/analysis.m). This is due to some path name changes. Find attached a version with changed paths and filenames:

[analysis.txt](https://github.com/PetaVision/OpenPV/files/1379782/analysis.txt)

Also the last part of the LCA-CIFAR-Tutorial.md has a problem which displays everything down line 244 as matlab code. This is due to a missing ` in line 253. Find attached a working file.

[LCA-CIFAR-Tutorial.txt](https://github.com/PetaVision/OpenPV/files/1379814/LCA-CIFAR-Tutorial.txt)

**Comment by peteschultz** [comment]
Thank you for finding and posting these fixes. Updated in commit <https://github.com/PetaVision/OpenPV/commit/5a9c9f8384a26275a7fbf4913496ffe370d1d9cc#diff-29a418c8385956c5269f365b90b89b3f> and <https://github.com/PetaVision/OpenPV/wiki/LCA-CIFAR-Tutorial>
