### ISSUE TITLE
Reorganizing tutorials & demos

### ISSUE THREAD

**Issue by dpaiton** [PetaVision/OpenPV#25]
I'd like to do some refactoring for the tutorials, examples, demos, etc. on our repository. Right now things are a little scattered.

Previously we had agreed via email on the following nomenclature: 
- Tutorials are designed to walk users through a feature or analysis or network in PetaVision. These are teaching materials.
- A demo should be an interface that is public facing, but hides the underpinnings. These are used to show off PetaVision. For example, the PetaVision classification web demo that @wshainin has been working on.

Below is the current situation:
## **Tutorial folder**

In the docs folder, there is a tutorial folder. I don't know who maintains this, although it is possible that I have contributed some of the items in it. This folder contains some text files that have explanations of various parameters, some images of example networks, and some outdated markdown files with tutorials on them. I say outdated because I believe they are replicated in the wiki. I'd like to deprecate this folder. Anything that looks worthy should be moved to the wiki if it isn't already replicated there. All else can be deleted.
## **Demo folder**

In the root, there is a demo folder. From what I can see, this folder contains:
- A tutorial on building an LCA network
- An octave demo for displaying PetaVision's PASCAL classification results
- total_energy_demo, which actually seems like a tutorial
- binocDemo, which @slundqui has confirmed is a real demo
## **Resolution**

To resolve this issue, I will move tutorials into OpenPV/tutorials and demos into OpenPV/demos. The demos folder will house code & images & such to create wiki demos as well as web demos. The tutorials folder will contain code for tutorials. Any document-based tutorial, like @slundqui's wiki post, will also host its files in the tutorials folder.

**Comment by wshainin** [comment]
The docs/tutorials folder is now removed from the develop branch. A 'tutorials' directory has been created, and tutorials that were in demo are now there. Demo is now 'demos'.
