### ISSUE TITLE
request to stop reading transpose, clone and other derived conns from checkpoints

### ISSUE THREAD

**Issue by garkenyon** [PetaVision/OpenPV#28]
right now, openPV reads transpose, clone, plasticClone and other derived conns from checkpoints.  Writing these files to checkpoint is supposedly optional (there's a flag to not checkpoint non-plastic conns).  It makes no sense to read these conns from checkpointed values regardless.   They're derived! Moreover, in implementing spatiotemporal kernels, it's convenient and useful to be able to encode sequences of video frames of arbitrary length using a fixed temporal kernel size and to be able to change the number of sequential frames encoded from one run to the next.  For example, the longer the sequence that were encoding in a given run, the more GPU memory we need.  Thus, on a single GPU, we can't encode as many frames at once as on multiple GPUs.  However, the longer the sequence we want to encode, the more clone conns or plastic clone conns we need.  Since all of these conns are derived, having to read their initial values from a checkpoint (if we're booting from a checkpoint) is annoying.  So why would I be booting from a checkpoint for a new run?  Checkpoints aren't guaranteed for that sort of thing (only for booting the same run from an intermediate point).   Well, see my recent bug report.  I can't read the state of a layer that's being updated on the GPU from a file.  So I'm cheating and booting from a checkpoint...

**Comment by peteschultz** [comment]
Just added a pull request to have TransposeConn and IdentConn do no checkpointing.  CloneConn and PlasticConn already override checkpointing to do nothing.

**Comment by slundqui** [comment]
Is this issue solved to the point where we can close this issue?

**Comment by peteschultz** [comment]
The pull request is still open; but I believe that if we merge it, we
could close this issue.  When Gar opened the issue, he referred to issue
#27, and that issue has not been resolved yet.

**Comment by peteschultz** [comment]
The most recent commit (19a997f) addresses this issue, so I'm closing it.
