### ISSUE TITLE
Refactor Python read(write)pvpfile code for speed

### ISSUE THREAD

**Issue by dpaiton** [PetaVision/OpenPV#33]
The Matlab analysis code for readpvpfile & writepvpfile are largely stuck how they are because of backward compatibility. However, the python code is still in its infancy and thus does not have a lot of other scripts that depend on it. I am proposing that we seize this opportunity to overhaul the pvtools scripts to utilize data structures that are optimized for speed and work well with the scipy/numpy libraries. When @maxtheiler created the new pvtools python utility, he focused on replicating the exact functionality and output structures of Matlab, as he was asked to do so. I think we should consider departing from the Matlab-style data structures. Those who wish to write analysis in Matlab may do so, but Python users should not be forced to use slower data structures just so that it is familiar to Matlab users.

I believe much of the work that Max put into the pvtools will not need to be redone. We just need to make sure that the outputs from readpvpfile are optimal numpy/scipy matrices, arrays, or sparse matrices. We would also need to refactor writepvpfile to expect these new data structures.

**Comment by slundqui** [comment]
I absolutely agree, please see issue #34, which is related to this.
