### ISSUE TITLE
Output state in Image.cpp

### ISSUE THREAD

**Issue by slundqui** [PetaVision/OpenPV#35]
Currently, Image.cpp is overwriting outputState to do nothing. Is this the desired result? I know the output of Image is not very interesting (as it loads an image and stays constant), but it would still be nice to be able to print out the pvp file if the end user wanted.

**Comment by peteschultz** [comment]
I agree that it would be useful for debugging and analysis purposes to have Image and ImagePvp be able to write a pvp output file.  Currently, they still read the writeStep parameter even though that parameter ends up having no effect.  Perhaps Image should use the base outputState, but have the default writeStep for Image be -1 (don't write)?  The default for writeStep from HyPerLayer is the column's dt (write every timestep).  If we do change the default for Image, we'd probably want to change it back for Movie.

**Comment by slundqui** [comment]
Fixed via commit 4e7b54bcec6bba2b3f7815e08d009d9f8f3b8e44
