### ISSUE TITLE
-t option is required when -n option is specified

### ISSUE THREAD

**Issue by garkenyon** [PetaVision/OpenPV#43]
if I am doing a dry run (-n command line option), I shouldn't need to specify a specific number of threads.  Currently, if no -t option is provided on the command line (and I compiled for openMP), running with -n throws an error.  Seems like the -t option should be required if -n is specified.  Perhaps -n should be processed before the other options that would be mooted?

**Comment by peteschultz** [comment]
I've added a pull request https://github.com/PetaVision/OpenPV/pull/45 that attempts to address this issue.

**Comment by peteschultz** [comment]
I've closed this issue, since https://github.com/PetaVision/OpenPV/pull/45 has been merged.
