### ISSUE TITLE
PVLog.hpp Info macro collides with OpenMPI Info class

### ISSUE THREAD

**Issue by peteschultz** [PetaVision/OpenPV#54]
If you #include PVLog.hpp and then #include mpi.h, there are compile errors during the preprocessing step because OpenMPI defines a class called Info, and PVLog.hpp has #defined a macro by the same name.

A workaround is to make sure that PVLog.hpp gets included only after mpi.h, but this is unsatisfactory because long trees of #includes make it difficult to tell what gets included in what order.

**Comment by slundqui** [comment]
Fixed with commit 630b9af

**Comment by peteschultz** [comment]
Thanks Sheng.  That fixed the problem.
