### ISSUE TITLE
HyPerLayer:: setInitialValues not called if HyPerCol defines an initialCheckpointDirectory even if Layer does not initialize from a checkpoint

### ISSUE THREAD

**Issue by garkenyon** [PetaVision/OpenPV#88]
HyPerLayer:: setInitialValues is not being called if HyPerCol defines an initialCheckpointDirectory, even if a Layer does not initialize from a checkpoint.  This bug breaks ConstantLayer completely but can have serious affects on all HyPerLayer instantiations.

**Comment by peteschultz** [comment]
Fixed by pull request #90.
